# Generated by Django 4.2.3 on 2023-07-26 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_notice_review_qna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_front', models.CharField(max_length=255)),
                ('address_back', models.CharField(max_length=255)),
                ('notices', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IsGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_soldout', models.BooleanField(default=False)),
                ('is_forsale', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.good')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IsGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_soldout', models.BooleanField(default=False)),
                ('is_forsale', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='issold',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='issold',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='defaultemail@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goods',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='types',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.DeleteModel(
            name='GoodsType',
        ),
        migrations.DeleteModel(
            name='IsSold',
        ),
        migrations.AddField(
            model_name='isgoods',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.goods'),
        ),
        migrations.AddField(
            model_name='good',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.goods'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
