# Generated by Django 4.2.3 on 2023-07-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_gender_user_nickname_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='01011111111', max_length=20),
        ),
    ]
