# Generated by Django 4.2.3 on 2023-07-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_token_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
