# Generated by Django 4.2.3 on 2023-07-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
