# Generated by Django 4.2.3 on 2023-07-27 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('myapp', '0011_remove_user_token_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='authtoken.token')),
                ('customkey', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Custom Key')),
                ('customcreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('customuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myapp_auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            bases=('authtoken.token',),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='myapp.customtoken'),
        ),
    ]
