# Generated by Django 4.2.3 on 2023-07-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_authtokentoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthtokenToken',
        ),
    ]
