# Generated by Django 4.2.3 on 2023-07-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_authtokentoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
