# Generated by Django 4.2.3 on 2023-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='customkey',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
