# Generated by Django 4.2.3 on 2023-07-28 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_customtoken_customkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='customcreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 0, 45, 36, tzinfo=datetime.timezone.utc)),
        ),
    ]
