# Generated by Django 4.2.3 on 2023-07-28 00:46

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_customtoken_customcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='customcreated',
            field=models.DateTimeField(default=myapp.models.utc_now_without_microseconds),
        ),
    ]
