# Generated by Django 4.2.3 on 2023-07-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_customtoken_customexp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtoken',
            name='customexp',
        ),
    ]
