# Generated by Django 4.2.3 on 2023-07-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_customtoken_customexp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField()),
                ('is_high_staff', models.BooleanField()),
                ('is_low_staff', models.BooleanField()),
            ],
        ),
    ]
