# Generated by Django 4.2.3 on 2023-07-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
