# Generated by Django 4.2.3 on 2023-07-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isgood',
            name='good',
        ),
        migrations.RemoveField(
            model_name='isgood',
            name='user',
        ),
        migrations.RemoveField(
            model_name='isgoods',
            name='goods',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='IsGood',
        ),
        migrations.DeleteModel(
            name='IsGoods',
        ),
    ]
