# Generated by Django 4.2.3 on 2023-07-31 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_isgood_good_remove_isgood_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.size')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.type')),
            ],
        ),
        migrations.CreateModel(
            name='Each_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('final_price', models.IntegerField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('each_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.each_product')),
            ],
        ),
    ]
