# Generated by Django 4.2.3 on 2023-09-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_cart_id_alter_discount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='each_product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='each_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='each_product',
            name='review',
        ),
        migrations.RemoveField(
            model_name='each_product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Each_Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
