# Generated by Django 4.2.3 on 2023-09-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_product_count_remove_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
